@setfilename domain-hc.info
@settitle domain-hc Utilities
@documentencoding UTF-8

@node Top
@top Directory Contents for domain-hc

@chapter Files

@table @file
@item check_domains.sh
This script checks domain availability.

@item delete_marker.sh
Script to delete old markers.

@item domain_status.log
Log file containing domain status updates.

@item domains_to_check
List of domains to be checked.

@item list_checks.sh
Script that lists all previous checks.
@end table

@bye

